name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install node modules
      run: npm i
    - name: Run ESLint
      run: npx eslint . --quiet

